version: "3.9"
services:
    rabbitmq:
        image: rabbitmq:3.8.17-management-alpine
        container_name: mq
        hostname: rabbitmq.local
        ports:
            - 5672:5672
            - 15672:15672
        env_file:
            prd.env
        security_opt:
            - seccomp:unconfined # 不加入此參數raspberry pi會出錯
    web:
        build:
            context: ./web
        container_name: web
        restart: always # 生錯誤重新啟動容器
        volumes:
            - /var/log/sexsexder:/usr/app/logs
        ports :
            - 5000:5000
        env_file:
            - prd.env
        depends_on:
            - rabbitmq
    worker:
        build:
            context: ./worker
        container_name: worker
        restart: always # 生錯誤重新啟動容器
        volumes:
            - /var/log/sexsexder:/usr/app/logs
            - /usr/data/sexsexder/downloads:/usr/app/downloads
            - ./session:/usr/app/session
        env_file:
            - prd.env
        depends_on:
            - rabbitmq