version: "3.9"
services:
    website:
        build:
            context: ./
            dockerfile: web/Dockerfile
        container_name: website.local
        restart: always # 生錯誤重新啟動容器
        volumes:
            - /var/log/sexsexder:/usr/app/logs
            - /usr/data/sexsexder/data:/usr/app/data
            - ./session:/usr/app/session
        ports :
            - 5000:5000
        env_file:
            - .env
    igdownloader:
        build:
            context: ./
            dockerfile: worker/igdownloader/Dockerfile
        container_name: igdownloader.local
        restart: always # 生錯誤重新啟動容器
        volumes:
            - /var/log/sexsexder:/usr/app/logs
            - /usr/data/sexsexder/downloads:/usr/app/downloads
            - ./session:/usr/app/session
            - /usr/data/sexsexder/data:/usr/app/data
        env_file:
            - .env
    fbposter:
        build:
            context: ./
            dockerfile: worker/fbposter/Dockerfile
        container_name: fbposter.local
        restart: always # 生錯誤重新啟動容器
        volumes:
            - /var/log/sexsexder:/usr/app/logs
            - /usr/data/sexsexder/downloads:/usr/app/downloads
            - ./session:/usr/app/session
            - /usr/data/sexsexder/data:/usr/app/data
        env_file:
            - .env
    mariadb:
        image: lscr.io/linuxserver/mariadb:10-jammy
        container_name: mariadb.local
        env_file:
            - .env
        volumes:
            - /usr/sexsexder/db:/config 
        ports:
            - 3306:3306
        restart: unless-stopped
